// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: volumes.proto
// Original file comments:
// #######################################################################
// ##- Copyright (c) Huawei Technologies Co., Ltd. 2020. All rights reserved.
// # - iSulad licensed under the Mulan PSL v2.
// # - You can use this software according to the terms and conditions of the Mulan PSL v2.
// # - You may obtain a copy of Mulan PSL v2 at:
// # -     http://license.coscl.org.cn/MulanPSL2
// # - THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
// # - IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
// # - PURPOSE.
// # - See the Mulan PSL v2 for more details.
// ##- @Description: generate grpc
// ##- @Author: wangfengtu
// ##- @Create: 2020-09-02
// #######################################################################
//
#ifndef GRPC_volumes_2eproto__INCLUDED
#define GRPC_volumes_2eproto__INCLUDED

#include "volumes.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace volume {

class VolumeService final {
 public:
  static constexpr char const* service_full_name() {
    return "volume.VolumeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status List(::grpc::ClientContext* context, const ::volume::ListVolumeRequest& request, ::volume::ListVolumeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::volume::ListVolumeResponse>> AsyncList(::grpc::ClientContext* context, const ::volume::ListVolumeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::volume::ListVolumeResponse>>(AsyncListRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::volume::ListVolumeResponse>> PrepareAsyncList(::grpc::ClientContext* context, const ::volume::ListVolumeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::volume::ListVolumeResponse>>(PrepareAsyncListRaw(context, request, cq));
    }
    virtual ::grpc::Status Remove(::grpc::ClientContext* context, const ::volume::RemoveVolumeRequest& request, ::volume::RemoveVolumeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::volume::RemoveVolumeResponse>> AsyncRemove(::grpc::ClientContext* context, const ::volume::RemoveVolumeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::volume::RemoveVolumeResponse>>(AsyncRemoveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::volume::RemoveVolumeResponse>> PrepareAsyncRemove(::grpc::ClientContext* context, const ::volume::RemoveVolumeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::volume::RemoveVolumeResponse>>(PrepareAsyncRemoveRaw(context, request, cq));
    }
    virtual ::grpc::Status Prune(::grpc::ClientContext* context, const ::volume::PruneVolumeRequest& request, ::volume::PruneVolumeResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::volume::PruneVolumeResponse>> AsyncPrune(::grpc::ClientContext* context, const ::volume::PruneVolumeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::volume::PruneVolumeResponse>>(AsyncPruneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::volume::PruneVolumeResponse>> PrepareAsyncPrune(::grpc::ClientContext* context, const ::volume::PruneVolumeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::volume::PruneVolumeResponse>>(PrepareAsyncPruneRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void List(::grpc::ClientContext* context, const ::volume::ListVolumeRequest* request, ::volume::ListVolumeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void List(::grpc::ClientContext* context, const ::volume::ListVolumeRequest* request, ::volume::ListVolumeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Remove(::grpc::ClientContext* context, const ::volume::RemoveVolumeRequest* request, ::volume::RemoveVolumeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Remove(::grpc::ClientContext* context, const ::volume::RemoveVolumeRequest* request, ::volume::RemoveVolumeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Prune(::grpc::ClientContext* context, const ::volume::PruneVolumeRequest* request, ::volume::PruneVolumeResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Prune(::grpc::ClientContext* context, const ::volume::PruneVolumeRequest* request, ::volume::PruneVolumeResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::volume::ListVolumeResponse>* AsyncListRaw(::grpc::ClientContext* context, const ::volume::ListVolumeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::volume::ListVolumeResponse>* PrepareAsyncListRaw(::grpc::ClientContext* context, const ::volume::ListVolumeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::volume::RemoveVolumeResponse>* AsyncRemoveRaw(::grpc::ClientContext* context, const ::volume::RemoveVolumeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::volume::RemoveVolumeResponse>* PrepareAsyncRemoveRaw(::grpc::ClientContext* context, const ::volume::RemoveVolumeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::volume::PruneVolumeResponse>* AsyncPruneRaw(::grpc::ClientContext* context, const ::volume::PruneVolumeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::volume::PruneVolumeResponse>* PrepareAsyncPruneRaw(::grpc::ClientContext* context, const ::volume::PruneVolumeRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status List(::grpc::ClientContext* context, const ::volume::ListVolumeRequest& request, ::volume::ListVolumeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::volume::ListVolumeResponse>> AsyncList(::grpc::ClientContext* context, const ::volume::ListVolumeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::volume::ListVolumeResponse>>(AsyncListRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::volume::ListVolumeResponse>> PrepareAsyncList(::grpc::ClientContext* context, const ::volume::ListVolumeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::volume::ListVolumeResponse>>(PrepareAsyncListRaw(context, request, cq));
    }
    ::grpc::Status Remove(::grpc::ClientContext* context, const ::volume::RemoveVolumeRequest& request, ::volume::RemoveVolumeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::volume::RemoveVolumeResponse>> AsyncRemove(::grpc::ClientContext* context, const ::volume::RemoveVolumeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::volume::RemoveVolumeResponse>>(AsyncRemoveRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::volume::RemoveVolumeResponse>> PrepareAsyncRemove(::grpc::ClientContext* context, const ::volume::RemoveVolumeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::volume::RemoveVolumeResponse>>(PrepareAsyncRemoveRaw(context, request, cq));
    }
    ::grpc::Status Prune(::grpc::ClientContext* context, const ::volume::PruneVolumeRequest& request, ::volume::PruneVolumeResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::volume::PruneVolumeResponse>> AsyncPrune(::grpc::ClientContext* context, const ::volume::PruneVolumeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::volume::PruneVolumeResponse>>(AsyncPruneRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::volume::PruneVolumeResponse>> PrepareAsyncPrune(::grpc::ClientContext* context, const ::volume::PruneVolumeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::volume::PruneVolumeResponse>>(PrepareAsyncPruneRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void List(::grpc::ClientContext* context, const ::volume::ListVolumeRequest* request, ::volume::ListVolumeResponse* response, std::function<void(::grpc::Status)>) override;
      void List(::grpc::ClientContext* context, const ::volume::ListVolumeRequest* request, ::volume::ListVolumeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Remove(::grpc::ClientContext* context, const ::volume::RemoveVolumeRequest* request, ::volume::RemoveVolumeResponse* response, std::function<void(::grpc::Status)>) override;
      void Remove(::grpc::ClientContext* context, const ::volume::RemoveVolumeRequest* request, ::volume::RemoveVolumeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Prune(::grpc::ClientContext* context, const ::volume::PruneVolumeRequest* request, ::volume::PruneVolumeResponse* response, std::function<void(::grpc::Status)>) override;
      void Prune(::grpc::ClientContext* context, const ::volume::PruneVolumeRequest* request, ::volume::PruneVolumeResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::volume::ListVolumeResponse>* AsyncListRaw(::grpc::ClientContext* context, const ::volume::ListVolumeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::volume::ListVolumeResponse>* PrepareAsyncListRaw(::grpc::ClientContext* context, const ::volume::ListVolumeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::volume::RemoveVolumeResponse>* AsyncRemoveRaw(::grpc::ClientContext* context, const ::volume::RemoveVolumeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::volume::RemoveVolumeResponse>* PrepareAsyncRemoveRaw(::grpc::ClientContext* context, const ::volume::RemoveVolumeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::volume::PruneVolumeResponse>* AsyncPruneRaw(::grpc::ClientContext* context, const ::volume::PruneVolumeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::volume::PruneVolumeResponse>* PrepareAsyncPruneRaw(::grpc::ClientContext* context, const ::volume::PruneVolumeRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_List_;
    const ::grpc::internal::RpcMethod rpcmethod_Remove_;
    const ::grpc::internal::RpcMethod rpcmethod_Prune_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status List(::grpc::ServerContext* context, const ::volume::ListVolumeRequest* request, ::volume::ListVolumeResponse* response);
    virtual ::grpc::Status Remove(::grpc::ServerContext* context, const ::volume::RemoveVolumeRequest* request, ::volume::RemoveVolumeResponse* response);
    virtual ::grpc::Status Prune(::grpc::ServerContext* context, const ::volume::PruneVolumeRequest* request, ::volume::PruneVolumeResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_List : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_List() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_List() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status List(::grpc::ServerContext* /*context*/, const ::volume::ListVolumeRequest* /*request*/, ::volume::ListVolumeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestList(::grpc::ServerContext* context, ::volume::ListVolumeRequest* request, ::grpc::ServerAsyncResponseWriter< ::volume::ListVolumeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Remove : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Remove() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Remove() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Remove(::grpc::ServerContext* /*context*/, const ::volume::RemoveVolumeRequest* /*request*/, ::volume::RemoveVolumeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRemove(::grpc::ServerContext* context, ::volume::RemoveVolumeRequest* request, ::grpc::ServerAsyncResponseWriter< ::volume::RemoveVolumeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Prune : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Prune() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_Prune() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Prune(::grpc::ServerContext* /*context*/, const ::volume::PruneVolumeRequest* /*request*/, ::volume::PruneVolumeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPrune(::grpc::ServerContext* context, ::volume::PruneVolumeRequest* request, ::grpc::ServerAsyncResponseWriter< ::volume::PruneVolumeResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_List<WithAsyncMethod_Remove<WithAsyncMethod_Prune<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_List : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_List() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::volume::ListVolumeRequest, ::volume::ListVolumeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::volume::ListVolumeRequest* request, ::volume::ListVolumeResponse* response) { return this->List(context, request, response); }));}
    void SetMessageAllocatorFor_List(
        ::grpc::MessageAllocator< ::volume::ListVolumeRequest, ::volume::ListVolumeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::volume::ListVolumeRequest, ::volume::ListVolumeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_List() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status List(::grpc::ServerContext* /*context*/, const ::volume::ListVolumeRequest* /*request*/, ::volume::ListVolumeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* List(
      ::grpc::CallbackServerContext* /*context*/, const ::volume::ListVolumeRequest* /*request*/, ::volume::ListVolumeResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Remove : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Remove() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::volume::RemoveVolumeRequest, ::volume::RemoveVolumeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::volume::RemoveVolumeRequest* request, ::volume::RemoveVolumeResponse* response) { return this->Remove(context, request, response); }));}
    void SetMessageAllocatorFor_Remove(
        ::grpc::MessageAllocator< ::volume::RemoveVolumeRequest, ::volume::RemoveVolumeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::volume::RemoveVolumeRequest, ::volume::RemoveVolumeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Remove() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Remove(::grpc::ServerContext* /*context*/, const ::volume::RemoveVolumeRequest* /*request*/, ::volume::RemoveVolumeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Remove(
      ::grpc::CallbackServerContext* /*context*/, const ::volume::RemoveVolumeRequest* /*request*/, ::volume::RemoveVolumeResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Prune : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Prune() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::volume::PruneVolumeRequest, ::volume::PruneVolumeResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::volume::PruneVolumeRequest* request, ::volume::PruneVolumeResponse* response) { return this->Prune(context, request, response); }));}
    void SetMessageAllocatorFor_Prune(
        ::grpc::MessageAllocator< ::volume::PruneVolumeRequest, ::volume::PruneVolumeResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::volume::PruneVolumeRequest, ::volume::PruneVolumeResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Prune() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Prune(::grpc::ServerContext* /*context*/, const ::volume::PruneVolumeRequest* /*request*/, ::volume::PruneVolumeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Prune(
      ::grpc::CallbackServerContext* /*context*/, const ::volume::PruneVolumeRequest* /*request*/, ::volume::PruneVolumeResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_List<WithCallbackMethod_Remove<WithCallbackMethod_Prune<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_List : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_List() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_List() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status List(::grpc::ServerContext* /*context*/, const ::volume::ListVolumeRequest* /*request*/, ::volume::ListVolumeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Remove : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Remove() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Remove() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Remove(::grpc::ServerContext* /*context*/, const ::volume::RemoveVolumeRequest* /*request*/, ::volume::RemoveVolumeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Prune : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Prune() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_Prune() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Prune(::grpc::ServerContext* /*context*/, const ::volume::PruneVolumeRequest* /*request*/, ::volume::PruneVolumeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_List : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_List() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_List() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status List(::grpc::ServerContext* /*context*/, const ::volume::ListVolumeRequest* /*request*/, ::volume::ListVolumeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestList(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Remove : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Remove() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Remove() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Remove(::grpc::ServerContext* /*context*/, const ::volume::RemoveVolumeRequest* /*request*/, ::volume::RemoveVolumeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRemove(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Prune : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Prune() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_Prune() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Prune(::grpc::ServerContext* /*context*/, const ::volume::PruneVolumeRequest* /*request*/, ::volume::PruneVolumeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPrune(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_List : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_List() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->List(context, request, response); }));
    }
    ~WithRawCallbackMethod_List() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status List(::grpc::ServerContext* /*context*/, const ::volume::ListVolumeRequest* /*request*/, ::volume::ListVolumeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* List(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Remove : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Remove() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Remove(context, request, response); }));
    }
    ~WithRawCallbackMethod_Remove() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Remove(::grpc::ServerContext* /*context*/, const ::volume::RemoveVolumeRequest* /*request*/, ::volume::RemoveVolumeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Remove(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Prune : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Prune() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Prune(context, request, response); }));
    }
    ~WithRawCallbackMethod_Prune() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Prune(::grpc::ServerContext* /*context*/, const ::volume::PruneVolumeRequest* /*request*/, ::volume::PruneVolumeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Prune(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_List : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_List() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::volume::ListVolumeRequest, ::volume::ListVolumeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::volume::ListVolumeRequest, ::volume::ListVolumeResponse>* streamer) {
                       return this->StreamedList(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_List() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status List(::grpc::ServerContext* /*context*/, const ::volume::ListVolumeRequest* /*request*/, ::volume::ListVolumeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedList(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::volume::ListVolumeRequest,::volume::ListVolumeResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Remove : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Remove() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::volume::RemoveVolumeRequest, ::volume::RemoveVolumeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::volume::RemoveVolumeRequest, ::volume::RemoveVolumeResponse>* streamer) {
                       return this->StreamedRemove(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Remove() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Remove(::grpc::ServerContext* /*context*/, const ::volume::RemoveVolumeRequest* /*request*/, ::volume::RemoveVolumeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRemove(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::volume::RemoveVolumeRequest,::volume::RemoveVolumeResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Prune : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Prune() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::volume::PruneVolumeRequest, ::volume::PruneVolumeResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::volume::PruneVolumeRequest, ::volume::PruneVolumeResponse>* streamer) {
                       return this->StreamedPrune(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Prune() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Prune(::grpc::ServerContext* /*context*/, const ::volume::PruneVolumeRequest* /*request*/, ::volume::PruneVolumeResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPrune(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::volume::PruneVolumeRequest,::volume::PruneVolumeResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_List<WithStreamedUnaryMethod_Remove<WithStreamedUnaryMethod_Prune<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_List<WithStreamedUnaryMethod_Remove<WithStreamedUnaryMethod_Prune<Service > > > StreamedService;
};

}  // namespace volume


#endif  // GRPC_volumes_2eproto__INCLUDED
