// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

#include "network.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_network_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_NetworkInfo_network_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_network_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_NetworkListRequest_FiltersEntry_DoNotUse_network_2eproto;
namespace network {
class NetworkInfoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<NetworkInfo> _instance;
} _NetworkInfo_default_instance_;
class NetworkCreateRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<NetworkCreateRequest> _instance;
} _NetworkCreateRequest_default_instance_;
class NetworkCreateResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<NetworkCreateResponse> _instance;
} _NetworkCreateResponse_default_instance_;
class NetworkInspectRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<NetworkInspectRequest> _instance;
} _NetworkInspectRequest_default_instance_;
class NetworkInspectResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<NetworkInspectResponse> _instance;
} _NetworkInspectResponse_default_instance_;
class NetworkListRequest_FiltersEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<NetworkListRequest_FiltersEntry_DoNotUse> _instance;
} _NetworkListRequest_FiltersEntry_DoNotUse_default_instance_;
class NetworkListRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<NetworkListRequest> _instance;
} _NetworkListRequest_default_instance_;
class NetworkListResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<NetworkListResponse> _instance;
} _NetworkListResponse_default_instance_;
class NetworkRemoveRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<NetworkRemoveRequest> _instance;
} _NetworkRemoveRequest_default_instance_;
class NetworkRemoveResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<NetworkRemoveResponse> _instance;
} _NetworkRemoveResponse_default_instance_;
}  // namespace network
static void InitDefaultsscc_info_NetworkCreateRequest_network_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::network::_NetworkCreateRequest_default_instance_;
    new (ptr) ::network::NetworkCreateRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_NetworkCreateRequest_network_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_NetworkCreateRequest_network_2eproto}, {}};

static void InitDefaultsscc_info_NetworkCreateResponse_network_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::network::_NetworkCreateResponse_default_instance_;
    new (ptr) ::network::NetworkCreateResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_NetworkCreateResponse_network_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_NetworkCreateResponse_network_2eproto}, {}};

static void InitDefaultsscc_info_NetworkInfo_network_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::network::_NetworkInfo_default_instance_;
    new (ptr) ::network::NetworkInfo();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_NetworkInfo_network_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_NetworkInfo_network_2eproto}, {}};

static void InitDefaultsscc_info_NetworkInspectRequest_network_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::network::_NetworkInspectRequest_default_instance_;
    new (ptr) ::network::NetworkInspectRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_NetworkInspectRequest_network_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_NetworkInspectRequest_network_2eproto}, {}};

static void InitDefaultsscc_info_NetworkInspectResponse_network_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::network::_NetworkInspectResponse_default_instance_;
    new (ptr) ::network::NetworkInspectResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_NetworkInspectResponse_network_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_NetworkInspectResponse_network_2eproto}, {}};

static void InitDefaultsscc_info_NetworkListRequest_network_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::network::_NetworkListRequest_default_instance_;
    new (ptr) ::network::NetworkListRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_NetworkListRequest_network_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_NetworkListRequest_network_2eproto}, {
      &scc_info_NetworkListRequest_FiltersEntry_DoNotUse_network_2eproto.base,}};

static void InitDefaultsscc_info_NetworkListRequest_FiltersEntry_DoNotUse_network_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::network::_NetworkListRequest_FiltersEntry_DoNotUse_default_instance_;
    new (ptr) ::network::NetworkListRequest_FiltersEntry_DoNotUse();
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_NetworkListRequest_FiltersEntry_DoNotUse_network_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_NetworkListRequest_FiltersEntry_DoNotUse_network_2eproto}, {}};

static void InitDefaultsscc_info_NetworkListResponse_network_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::network::_NetworkListResponse_default_instance_;
    new (ptr) ::network::NetworkListResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_NetworkListResponse_network_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_NetworkListResponse_network_2eproto}, {
      &scc_info_NetworkInfo_network_2eproto.base,}};

static void InitDefaultsscc_info_NetworkRemoveRequest_network_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::network::_NetworkRemoveRequest_default_instance_;
    new (ptr) ::network::NetworkRemoveRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_NetworkRemoveRequest_network_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_NetworkRemoveRequest_network_2eproto}, {}};

static void InitDefaultsscc_info_NetworkRemoveResponse_network_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::network::_NetworkRemoveResponse_default_instance_;
    new (ptr) ::network::NetworkRemoveResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_NetworkRemoveResponse_network_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_NetworkRemoveResponse_network_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_network_2eproto[10];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_network_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_network_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_network_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::network::NetworkInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::network::NetworkInfo, name_),
  PROTOBUF_FIELD_OFFSET(::network::NetworkInfo, version_),
  PROTOBUF_FIELD_OFFSET(::network::NetworkInfo, plugins_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::network::NetworkCreateRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::network::NetworkCreateRequest, name_),
  PROTOBUF_FIELD_OFFSET(::network::NetworkCreateRequest, driver_),
  PROTOBUF_FIELD_OFFSET(::network::NetworkCreateRequest, gateway_),
  PROTOBUF_FIELD_OFFSET(::network::NetworkCreateRequest, internal_),
  PROTOBUF_FIELD_OFFSET(::network::NetworkCreateRequest, subnet_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::network::NetworkCreateResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::network::NetworkCreateResponse, name_),
  PROTOBUF_FIELD_OFFSET(::network::NetworkCreateResponse, cc_),
  PROTOBUF_FIELD_OFFSET(::network::NetworkCreateResponse, errmsg_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::network::NetworkInspectRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::network::NetworkInspectRequest, name_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::network::NetworkInspectResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::network::NetworkInspectResponse, networkjson_),
  PROTOBUF_FIELD_OFFSET(::network::NetworkInspectResponse, cc_),
  PROTOBUF_FIELD_OFFSET(::network::NetworkInspectResponse, errmsg_),
  PROTOBUF_FIELD_OFFSET(::network::NetworkListRequest_FiltersEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::network::NetworkListRequest_FiltersEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::network::NetworkListRequest_FiltersEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::network::NetworkListRequest_FiltersEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::network::NetworkListRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::network::NetworkListRequest, filters_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::network::NetworkListResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::network::NetworkListResponse, networks_),
  PROTOBUF_FIELD_OFFSET(::network::NetworkListResponse, cc_),
  PROTOBUF_FIELD_OFFSET(::network::NetworkListResponse, errmsg_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::network::NetworkRemoveRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::network::NetworkRemoveRequest, name_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::network::NetworkRemoveResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::network::NetworkRemoveResponse, name_),
  PROTOBUF_FIELD_OFFSET(::network::NetworkRemoveResponse, cc_),
  PROTOBUF_FIELD_OFFSET(::network::NetworkRemoveResponse, errmsg_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::network::NetworkInfo)},
  { 8, -1, sizeof(::network::NetworkCreateRequest)},
  { 18, -1, sizeof(::network::NetworkCreateResponse)},
  { 26, -1, sizeof(::network::NetworkInspectRequest)},
  { 32, -1, sizeof(::network::NetworkInspectResponse)},
  { 40, 47, sizeof(::network::NetworkListRequest_FiltersEntry_DoNotUse)},
  { 49, -1, sizeof(::network::NetworkListRequest)},
  { 55, -1, sizeof(::network::NetworkListResponse)},
  { 63, -1, sizeof(::network::NetworkRemoveRequest)},
  { 69, -1, sizeof(::network::NetworkRemoveResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::network::_NetworkInfo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::network::_NetworkCreateRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::network::_NetworkCreateResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::network::_NetworkInspectRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::network::_NetworkInspectResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::network::_NetworkListRequest_FiltersEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::network::_NetworkListRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::network::_NetworkListResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::network::_NetworkRemoveRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::network::_NetworkRemoveResponse_default_instance_),
};

const char descriptor_table_protodef_network_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rnetwork.proto\022\007network\"=\n\013NetworkInfo\022"
  "\014\n\004name\030\001 \001(\t\022\017\n\007version\030\002 \001(\t\022\017\n\007plugin"
  "s\030\003 \003(\t\"g\n\024NetworkCreateRequest\022\014\n\004name\030"
  "\001 \001(\t\022\016\n\006driver\030\002 \001(\t\022\017\n\007gateway\030\003 \001(\t\022\020"
  "\n\010internal\030\004 \001(\010\022\016\n\006subnet\030\005 \001(\t\"A\n\025Netw"
  "orkCreateResponse\022\014\n\004name\030\001 \001(\t\022\n\n\002cc\030\002 "
  "\001(\r\022\016\n\006errmsg\030\003 \001(\t\"%\n\025NetworkInspectReq"
  "uest\022\014\n\004name\030\001 \001(\t\"I\n\026NetworkInspectResp"
  "onse\022\023\n\013NetworkJSON\030\001 \001(\t\022\n\n\002cc\030\002 \001(\r\022\016\n"
  "\006errmsg\030\003 \001(\t\"\177\n\022NetworkListRequest\0229\n\007f"
  "ilters\030\001 \003(\0132(.network.NetworkListReques"
  "t.FiltersEntry\032.\n\014FiltersEntry\022\013\n\003key\030\001 "
  "\001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"Y\n\023NetworkListRes"
  "ponse\022&\n\010networks\030\001 \003(\0132\024.network.Networ"
  "kInfo\022\n\n\002cc\030\002 \001(\r\022\016\n\006errmsg\030\003 \001(\t\"$\n\024Net"
  "workRemoveRequest\022\014\n\004name\030\001 \001(\t\"A\n\025Netwo"
  "rkRemoveResponse\022\014\n\004name\030\001 \001(\t\022\n\n\002cc\030\002 \001"
  "(\r\022\016\n\006errmsg\030\003 \001(\t2\261\002\n\016NetworkService\022G\n"
  "\006Create\022\035.network.NetworkCreateRequest\032\036"
  ".network.NetworkCreateResponse\022J\n\007Inspec"
  "t\022\036.network.NetworkInspectRequest\032\037.netw"
  "ork.NetworkInspectResponse\022A\n\004List\022\033.net"
  "work.NetworkListRequest\032\034.network.Networ"
  "kListResponse\022G\n\006Remove\022\035.network.Networ"
  "kRemoveRequest\032\036.network.NetworkRemoveRe"
  "sponseB\002H\002b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_network_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_network_2eproto_sccs[10] = {
  &scc_info_NetworkCreateRequest_network_2eproto.base,
  &scc_info_NetworkCreateResponse_network_2eproto.base,
  &scc_info_NetworkInfo_network_2eproto.base,
  &scc_info_NetworkInspectRequest_network_2eproto.base,
  &scc_info_NetworkInspectResponse_network_2eproto.base,
  &scc_info_NetworkListRequest_network_2eproto.base,
  &scc_info_NetworkListRequest_FiltersEntry_DoNotUse_network_2eproto.base,
  &scc_info_NetworkListResponse_network_2eproto.base,
  &scc_info_NetworkRemoveRequest_network_2eproto.base,
  &scc_info_NetworkRemoveResponse_network_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_network_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_network_2eproto = {
  false, false, descriptor_table_protodef_network_2eproto, "network.proto", 1018,
  &descriptor_table_network_2eproto_once, descriptor_table_network_2eproto_sccs, descriptor_table_network_2eproto_deps, 10, 0,
  schemas, file_default_instances, TableStruct_network_2eproto::offsets,
  file_level_metadata_network_2eproto, 10, file_level_enum_descriptors_network_2eproto, file_level_service_descriptors_network_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_network_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_network_2eproto)), true);
namespace network {

// ===================================================================

class NetworkInfo::_Internal {
 public:
};

NetworkInfo::NetworkInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  plugins_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:network.NetworkInfo)
}
NetworkInfo::NetworkInfo(const NetworkInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      plugins_(from.plugins_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_name(), 
      GetArena());
  }
  version_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_version().empty()) {
    version_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_version(), 
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:network.NetworkInfo)
}

void NetworkInfo::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_NetworkInfo_network_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  version_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

NetworkInfo::~NetworkInfo() {
  // @@protoc_insertion_point(destructor:network.NetworkInfo)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void NetworkInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  version_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void NetworkInfo::ArenaDtor(void* object) {
  NetworkInfo* _this = reinterpret_cast< NetworkInfo* >(object);
  (void)_this;
}
void NetworkInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NetworkInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const NetworkInfo& NetworkInfo::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_NetworkInfo_network_2eproto.base);
  return *internal_default_instance();
}


void NetworkInfo::InternalSwap(NetworkInfo* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata NetworkInfo::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class NetworkCreateRequest::_Internal {
 public:
};

NetworkCreateRequest::NetworkCreateRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:network.NetworkCreateRequest)
}
NetworkCreateRequest::NetworkCreateRequest(const NetworkCreateRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_name(), 
      GetArena());
  }
  driver_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_driver().empty()) {
    driver_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_driver(), 
      GetArena());
  }
  gateway_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_gateway().empty()) {
    gateway_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_gateway(), 
      GetArena());
  }
  subnet_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_subnet().empty()) {
    subnet_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_subnet(), 
      GetArena());
  }
  internal_ = from.internal_;
  // @@protoc_insertion_point(copy_constructor:network.NetworkCreateRequest)
}

void NetworkCreateRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_NetworkCreateRequest_network_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  driver_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  gateway_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  subnet_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  internal_ = false;
}

NetworkCreateRequest::~NetworkCreateRequest() {
  // @@protoc_insertion_point(destructor:network.NetworkCreateRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void NetworkCreateRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  driver_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  gateway_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  subnet_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void NetworkCreateRequest::ArenaDtor(void* object) {
  NetworkCreateRequest* _this = reinterpret_cast< NetworkCreateRequest* >(object);
  (void)_this;
}
void NetworkCreateRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NetworkCreateRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const NetworkCreateRequest& NetworkCreateRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_NetworkCreateRequest_network_2eproto.base);
  return *internal_default_instance();
}


void NetworkCreateRequest::InternalSwap(NetworkCreateRequest* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata NetworkCreateRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class NetworkCreateResponse::_Internal {
 public:
};

NetworkCreateResponse::NetworkCreateResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:network.NetworkCreateResponse)
}
NetworkCreateResponse::NetworkCreateResponse(const NetworkCreateResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_name(), 
      GetArena());
  }
  errmsg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_errmsg().empty()) {
    errmsg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_errmsg(), 
      GetArena());
  }
  cc_ = from.cc_;
  // @@protoc_insertion_point(copy_constructor:network.NetworkCreateResponse)
}

void NetworkCreateResponse::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_NetworkCreateResponse_network_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  errmsg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  cc_ = 0u;
}

NetworkCreateResponse::~NetworkCreateResponse() {
  // @@protoc_insertion_point(destructor:network.NetworkCreateResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void NetworkCreateResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  errmsg_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void NetworkCreateResponse::ArenaDtor(void* object) {
  NetworkCreateResponse* _this = reinterpret_cast< NetworkCreateResponse* >(object);
  (void)_this;
}
void NetworkCreateResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NetworkCreateResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const NetworkCreateResponse& NetworkCreateResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_NetworkCreateResponse_network_2eproto.base);
  return *internal_default_instance();
}


void NetworkCreateResponse::InternalSwap(NetworkCreateResponse* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata NetworkCreateResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class NetworkInspectRequest::_Internal {
 public:
};

NetworkInspectRequest::NetworkInspectRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:network.NetworkInspectRequest)
}
NetworkInspectRequest::NetworkInspectRequest(const NetworkInspectRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_name(), 
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:network.NetworkInspectRequest)
}

void NetworkInspectRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_NetworkInspectRequest_network_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

NetworkInspectRequest::~NetworkInspectRequest() {
  // @@protoc_insertion_point(destructor:network.NetworkInspectRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void NetworkInspectRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void NetworkInspectRequest::ArenaDtor(void* object) {
  NetworkInspectRequest* _this = reinterpret_cast< NetworkInspectRequest* >(object);
  (void)_this;
}
void NetworkInspectRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NetworkInspectRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const NetworkInspectRequest& NetworkInspectRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_NetworkInspectRequest_network_2eproto.base);
  return *internal_default_instance();
}


void NetworkInspectRequest::InternalSwap(NetworkInspectRequest* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata NetworkInspectRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class NetworkInspectResponse::_Internal {
 public:
};

NetworkInspectResponse::NetworkInspectResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:network.NetworkInspectResponse)
}
NetworkInspectResponse::NetworkInspectResponse(const NetworkInspectResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  networkjson_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_networkjson().empty()) {
    networkjson_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_networkjson(), 
      GetArena());
  }
  errmsg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_errmsg().empty()) {
    errmsg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_errmsg(), 
      GetArena());
  }
  cc_ = from.cc_;
  // @@protoc_insertion_point(copy_constructor:network.NetworkInspectResponse)
}

void NetworkInspectResponse::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_NetworkInspectResponse_network_2eproto.base);
  networkjson_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  errmsg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  cc_ = 0u;
}

NetworkInspectResponse::~NetworkInspectResponse() {
  // @@protoc_insertion_point(destructor:network.NetworkInspectResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void NetworkInspectResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  networkjson_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  errmsg_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void NetworkInspectResponse::ArenaDtor(void* object) {
  NetworkInspectResponse* _this = reinterpret_cast< NetworkInspectResponse* >(object);
  (void)_this;
}
void NetworkInspectResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NetworkInspectResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const NetworkInspectResponse& NetworkInspectResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_NetworkInspectResponse_network_2eproto.base);
  return *internal_default_instance();
}


void NetworkInspectResponse::InternalSwap(NetworkInspectResponse* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata NetworkInspectResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

NetworkListRequest_FiltersEntry_DoNotUse::NetworkListRequest_FiltersEntry_DoNotUse() {}
NetworkListRequest_FiltersEntry_DoNotUse::NetworkListRequest_FiltersEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void NetworkListRequest_FiltersEntry_DoNotUse::MergeFrom(const NetworkListRequest_FiltersEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata NetworkListRequest_FiltersEntry_DoNotUse::GetMetadata() const {
  return GetMetadataStatic();
}
void NetworkListRequest_FiltersEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::Message& other) {
  ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom(other);
}


// ===================================================================

class NetworkListRequest::_Internal {
 public:
};

NetworkListRequest::NetworkListRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  filters_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:network.NetworkListRequest)
}
NetworkListRequest::NetworkListRequest(const NetworkListRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  filters_.MergeFrom(from.filters_);
  // @@protoc_insertion_point(copy_constructor:network.NetworkListRequest)
}

void NetworkListRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_NetworkListRequest_network_2eproto.base);
}

NetworkListRequest::~NetworkListRequest() {
  // @@protoc_insertion_point(destructor:network.NetworkListRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void NetworkListRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void NetworkListRequest::ArenaDtor(void* object) {
  NetworkListRequest* _this = reinterpret_cast< NetworkListRequest* >(object);
  (void)_this;
}
void NetworkListRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NetworkListRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const NetworkListRequest& NetworkListRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_NetworkListRequest_network_2eproto.base);
  return *internal_default_instance();
}


void NetworkListRequest::InternalSwap(NetworkListRequest* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata NetworkListRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class NetworkListResponse::_Internal {
 public:
};

NetworkListResponse::NetworkListResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  networks_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:network.NetworkListResponse)
}
NetworkListResponse::NetworkListResponse(const NetworkListResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      networks_(from.networks_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  errmsg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_errmsg().empty()) {
    errmsg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_errmsg(), 
      GetArena());
  }
  cc_ = from.cc_;
  // @@protoc_insertion_point(copy_constructor:network.NetworkListResponse)
}

void NetworkListResponse::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_NetworkListResponse_network_2eproto.base);
  errmsg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  cc_ = 0u;
}

NetworkListResponse::~NetworkListResponse() {
  // @@protoc_insertion_point(destructor:network.NetworkListResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void NetworkListResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  errmsg_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void NetworkListResponse::ArenaDtor(void* object) {
  NetworkListResponse* _this = reinterpret_cast< NetworkListResponse* >(object);
  (void)_this;
}
void NetworkListResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NetworkListResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const NetworkListResponse& NetworkListResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_NetworkListResponse_network_2eproto.base);
  return *internal_default_instance();
}


void NetworkListResponse::InternalSwap(NetworkListResponse* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata NetworkListResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class NetworkRemoveRequest::_Internal {
 public:
};

NetworkRemoveRequest::NetworkRemoveRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:network.NetworkRemoveRequest)
}
NetworkRemoveRequest::NetworkRemoveRequest(const NetworkRemoveRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_name(), 
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:network.NetworkRemoveRequest)
}

void NetworkRemoveRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_NetworkRemoveRequest_network_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

NetworkRemoveRequest::~NetworkRemoveRequest() {
  // @@protoc_insertion_point(destructor:network.NetworkRemoveRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void NetworkRemoveRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void NetworkRemoveRequest::ArenaDtor(void* object) {
  NetworkRemoveRequest* _this = reinterpret_cast< NetworkRemoveRequest* >(object);
  (void)_this;
}
void NetworkRemoveRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NetworkRemoveRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const NetworkRemoveRequest& NetworkRemoveRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_NetworkRemoveRequest_network_2eproto.base);
  return *internal_default_instance();
}


void NetworkRemoveRequest::InternalSwap(NetworkRemoveRequest* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata NetworkRemoveRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class NetworkRemoveResponse::_Internal {
 public:
};

NetworkRemoveResponse::NetworkRemoveResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:network.NetworkRemoveResponse)
}
NetworkRemoveResponse::NetworkRemoveResponse(const NetworkRemoveResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_name(), 
      GetArena());
  }
  errmsg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_errmsg().empty()) {
    errmsg_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_errmsg(), 
      GetArena());
  }
  cc_ = from.cc_;
  // @@protoc_insertion_point(copy_constructor:network.NetworkRemoveResponse)
}

void NetworkRemoveResponse::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_NetworkRemoveResponse_network_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  errmsg_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  cc_ = 0u;
}

NetworkRemoveResponse::~NetworkRemoveResponse() {
  // @@protoc_insertion_point(destructor:network.NetworkRemoveResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void NetworkRemoveResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  errmsg_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void NetworkRemoveResponse::ArenaDtor(void* object) {
  NetworkRemoveResponse* _this = reinterpret_cast< NetworkRemoveResponse* >(object);
  (void)_this;
}
void NetworkRemoveResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NetworkRemoveResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const NetworkRemoveResponse& NetworkRemoveResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_NetworkRemoveResponse_network_2eproto.base);
  return *internal_default_instance();
}


void NetworkRemoveResponse::InternalSwap(NetworkRemoveResponse* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata NetworkRemoveResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace network
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::network::NetworkInfo* Arena::CreateMaybeMessage< ::network::NetworkInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::network::NetworkInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::network::NetworkCreateRequest* Arena::CreateMaybeMessage< ::network::NetworkCreateRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::network::NetworkCreateRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::network::NetworkCreateResponse* Arena::CreateMaybeMessage< ::network::NetworkCreateResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::network::NetworkCreateResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::network::NetworkInspectRequest* Arena::CreateMaybeMessage< ::network::NetworkInspectRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::network::NetworkInspectRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::network::NetworkInspectResponse* Arena::CreateMaybeMessage< ::network::NetworkInspectResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::network::NetworkInspectResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::network::NetworkListRequest_FiltersEntry_DoNotUse* Arena::CreateMaybeMessage< ::network::NetworkListRequest_FiltersEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::network::NetworkListRequest_FiltersEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::network::NetworkListRequest* Arena::CreateMaybeMessage< ::network::NetworkListRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::network::NetworkListRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::network::NetworkListResponse* Arena::CreateMaybeMessage< ::network::NetworkListResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::network::NetworkListResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::network::NetworkRemoveRequest* Arena::CreateMaybeMessage< ::network::NetworkRemoveRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::network::NetworkRemoveRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::network::NetworkRemoveResponse* Arena::CreateMaybeMessage< ::network::NetworkRemoveResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::network::NetworkRemoveResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
