// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: container.proto

#include "container.pb.h"
#include "container.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace containers {

static const char* ContainerService_method_names[] = {
  "/containers.ContainerService/Create",
  "/containers.ContainerService/Start",
  "/containers.ContainerService/RemoteStart",
  "/containers.ContainerService/Top",
  "/containers.ContainerService/Stop",
  "/containers.ContainerService/Kill",
  "/containers.ContainerService/Delete",
  "/containers.ContainerService/Pause",
  "/containers.ContainerService/Resume",
  "/containers.ContainerService/Inspect",
  "/containers.ContainerService/List",
  "/containers.ContainerService/Stats",
  "/containers.ContainerService/Wait",
  "/containers.ContainerService/Events",
  "/containers.ContainerService/Exec",
  "/containers.ContainerService/RemoteExec",
  "/containers.ContainerService/Version",
  "/containers.ContainerService/Info",
  "/containers.ContainerService/Update",
  "/containers.ContainerService/Attach",
  "/containers.ContainerService/Restart",
  "/containers.ContainerService/Export",
  "/containers.ContainerService/CopyFromContainer",
  "/containers.ContainerService/CopyToContainer",
  "/containers.ContainerService/Rename",
  "/containers.ContainerService/Logs",
  "/containers.ContainerService/Resize",
};

std::unique_ptr< ContainerService::Stub> ContainerService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ContainerService::Stub> stub(new ContainerService::Stub(channel, options));
  return stub;
}

ContainerService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Create_(ContainerService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Start_(ContainerService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RemoteStart_(ContainerService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_Top_(ContainerService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Stop_(ContainerService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Kill_(ContainerService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Delete_(ContainerService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Pause_(ContainerService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Resume_(ContainerService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Inspect_(ContainerService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_List_(ContainerService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Stats_(ContainerService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Wait_(ContainerService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Events_(ContainerService_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_Exec_(ContainerService_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RemoteExec_(ContainerService_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_Version_(ContainerService_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Info_(ContainerService_method_names[17], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Update_(ContainerService_method_names[18], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Attach_(ContainerService_method_names[19], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_Restart_(ContainerService_method_names[20], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Export_(ContainerService_method_names[21], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CopyFromContainer_(ContainerService_method_names[22], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_CopyToContainer_(ContainerService_method_names[23], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_Rename_(ContainerService_method_names[24], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Logs_(ContainerService_method_names[25], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_Resize_(ContainerService_method_names[26], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ContainerService::Stub::Create(::grpc::ClientContext* context, const ::containers::CreateRequest& request, ::containers::CreateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::CreateRequest, ::containers::CreateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Create_, context, request, response);
}

void ContainerService::Stub::async::Create(::grpc::ClientContext* context, const ::containers::CreateRequest* request, ::containers::CreateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::CreateRequest, ::containers::CreateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Create_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::Create(::grpc::ClientContext* context, const ::containers::CreateRequest* request, ::containers::CreateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Create_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::CreateResponse>* ContainerService::Stub::PrepareAsyncCreateRaw(::grpc::ClientContext* context, const ::containers::CreateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::CreateResponse, ::containers::CreateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Create_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::CreateResponse>* ContainerService::Stub::AsyncCreateRaw(::grpc::ClientContext* context, const ::containers::CreateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ContainerService::Stub::Start(::grpc::ClientContext* context, const ::containers::StartRequest& request, ::containers::StartResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::StartRequest, ::containers::StartResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Start_, context, request, response);
}

void ContainerService::Stub::async::Start(::grpc::ClientContext* context, const ::containers::StartRequest* request, ::containers::StartResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::StartRequest, ::containers::StartResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Start_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::Start(::grpc::ClientContext* context, const ::containers::StartRequest* request, ::containers::StartResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Start_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::StartResponse>* ContainerService::Stub::PrepareAsyncStartRaw(::grpc::ClientContext* context, const ::containers::StartRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::StartResponse, ::containers::StartRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Start_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::StartResponse>* ContainerService::Stub::AsyncStartRaw(::grpc::ClientContext* context, const ::containers::StartRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStartRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::containers::RemoteStartRequest, ::containers::RemoteStartResponse>* ContainerService::Stub::RemoteStartRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::containers::RemoteStartRequest, ::containers::RemoteStartResponse>::Create(channel_.get(), rpcmethod_RemoteStart_, context);
}

void ContainerService::Stub::async::RemoteStart(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::containers::RemoteStartRequest,::containers::RemoteStartResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::containers::RemoteStartRequest,::containers::RemoteStartResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_RemoteStart_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::containers::RemoteStartRequest, ::containers::RemoteStartResponse>* ContainerService::Stub::AsyncRemoteStartRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::containers::RemoteStartRequest, ::containers::RemoteStartResponse>::Create(channel_.get(), cq, rpcmethod_RemoteStart_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::containers::RemoteStartRequest, ::containers::RemoteStartResponse>* ContainerService::Stub::PrepareAsyncRemoteStartRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::containers::RemoteStartRequest, ::containers::RemoteStartResponse>::Create(channel_.get(), cq, rpcmethod_RemoteStart_, context, false, nullptr);
}

::grpc::Status ContainerService::Stub::Top(::grpc::ClientContext* context, const ::containers::TopRequest& request, ::containers::TopResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::TopRequest, ::containers::TopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Top_, context, request, response);
}

void ContainerService::Stub::async::Top(::grpc::ClientContext* context, const ::containers::TopRequest* request, ::containers::TopResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::TopRequest, ::containers::TopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Top_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::Top(::grpc::ClientContext* context, const ::containers::TopRequest* request, ::containers::TopResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Top_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::TopResponse>* ContainerService::Stub::PrepareAsyncTopRaw(::grpc::ClientContext* context, const ::containers::TopRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::TopResponse, ::containers::TopRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Top_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::TopResponse>* ContainerService::Stub::AsyncTopRaw(::grpc::ClientContext* context, const ::containers::TopRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTopRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ContainerService::Stub::Stop(::grpc::ClientContext* context, const ::containers::StopRequest& request, ::containers::StopResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::StopRequest, ::containers::StopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Stop_, context, request, response);
}

void ContainerService::Stub::async::Stop(::grpc::ClientContext* context, const ::containers::StopRequest* request, ::containers::StopResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::StopRequest, ::containers::StopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Stop_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::Stop(::grpc::ClientContext* context, const ::containers::StopRequest* request, ::containers::StopResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Stop_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::StopResponse>* ContainerService::Stub::PrepareAsyncStopRaw(::grpc::ClientContext* context, const ::containers::StopRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::StopResponse, ::containers::StopRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Stop_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::StopResponse>* ContainerService::Stub::AsyncStopRaw(::grpc::ClientContext* context, const ::containers::StopRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStopRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ContainerService::Stub::Kill(::grpc::ClientContext* context, const ::containers::KillRequest& request, ::containers::KillResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::KillRequest, ::containers::KillResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Kill_, context, request, response);
}

void ContainerService::Stub::async::Kill(::grpc::ClientContext* context, const ::containers::KillRequest* request, ::containers::KillResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::KillRequest, ::containers::KillResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Kill_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::Kill(::grpc::ClientContext* context, const ::containers::KillRequest* request, ::containers::KillResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Kill_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::KillResponse>* ContainerService::Stub::PrepareAsyncKillRaw(::grpc::ClientContext* context, const ::containers::KillRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::KillResponse, ::containers::KillRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Kill_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::KillResponse>* ContainerService::Stub::AsyncKillRaw(::grpc::ClientContext* context, const ::containers::KillRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncKillRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ContainerService::Stub::Delete(::grpc::ClientContext* context, const ::containers::DeleteRequest& request, ::containers::DeleteResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::DeleteRequest, ::containers::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Delete_, context, request, response);
}

void ContainerService::Stub::async::Delete(::grpc::ClientContext* context, const ::containers::DeleteRequest* request, ::containers::DeleteResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::DeleteRequest, ::containers::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::Delete(::grpc::ClientContext* context, const ::containers::DeleteRequest* request, ::containers::DeleteResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Delete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::DeleteResponse>* ContainerService::Stub::PrepareAsyncDeleteRaw(::grpc::ClientContext* context, const ::containers::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::DeleteResponse, ::containers::DeleteRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Delete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::DeleteResponse>* ContainerService::Stub::AsyncDeleteRaw(::grpc::ClientContext* context, const ::containers::DeleteRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ContainerService::Stub::Pause(::grpc::ClientContext* context, const ::containers::PauseRequest& request, ::containers::PauseResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::PauseRequest, ::containers::PauseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Pause_, context, request, response);
}

void ContainerService::Stub::async::Pause(::grpc::ClientContext* context, const ::containers::PauseRequest* request, ::containers::PauseResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::PauseRequest, ::containers::PauseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Pause_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::Pause(::grpc::ClientContext* context, const ::containers::PauseRequest* request, ::containers::PauseResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Pause_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::PauseResponse>* ContainerService::Stub::PrepareAsyncPauseRaw(::grpc::ClientContext* context, const ::containers::PauseRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::PauseResponse, ::containers::PauseRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Pause_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::PauseResponse>* ContainerService::Stub::AsyncPauseRaw(::grpc::ClientContext* context, const ::containers::PauseRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPauseRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ContainerService::Stub::Resume(::grpc::ClientContext* context, const ::containers::ResumeRequest& request, ::containers::ResumeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::ResumeRequest, ::containers::ResumeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Resume_, context, request, response);
}

void ContainerService::Stub::async::Resume(::grpc::ClientContext* context, const ::containers::ResumeRequest* request, ::containers::ResumeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::ResumeRequest, ::containers::ResumeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Resume_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::Resume(::grpc::ClientContext* context, const ::containers::ResumeRequest* request, ::containers::ResumeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Resume_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::ResumeResponse>* ContainerService::Stub::PrepareAsyncResumeRaw(::grpc::ClientContext* context, const ::containers::ResumeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::ResumeResponse, ::containers::ResumeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Resume_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::ResumeResponse>* ContainerService::Stub::AsyncResumeRaw(::grpc::ClientContext* context, const ::containers::ResumeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncResumeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ContainerService::Stub::Inspect(::grpc::ClientContext* context, const ::containers::InspectContainerRequest& request, ::containers::InspectContainerResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::InspectContainerRequest, ::containers::InspectContainerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Inspect_, context, request, response);
}

void ContainerService::Stub::async::Inspect(::grpc::ClientContext* context, const ::containers::InspectContainerRequest* request, ::containers::InspectContainerResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::InspectContainerRequest, ::containers::InspectContainerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Inspect_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::Inspect(::grpc::ClientContext* context, const ::containers::InspectContainerRequest* request, ::containers::InspectContainerResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Inspect_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::InspectContainerResponse>* ContainerService::Stub::PrepareAsyncInspectRaw(::grpc::ClientContext* context, const ::containers::InspectContainerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::InspectContainerResponse, ::containers::InspectContainerRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Inspect_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::InspectContainerResponse>* ContainerService::Stub::AsyncInspectRaw(::grpc::ClientContext* context, const ::containers::InspectContainerRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInspectRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ContainerService::Stub::List(::grpc::ClientContext* context, const ::containers::ListRequest& request, ::containers::ListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::ListRequest, ::containers::ListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_List_, context, request, response);
}

void ContainerService::Stub::async::List(::grpc::ClientContext* context, const ::containers::ListRequest* request, ::containers::ListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::ListRequest, ::containers::ListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_List_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::List(::grpc::ClientContext* context, const ::containers::ListRequest* request, ::containers::ListResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_List_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::ListResponse>* ContainerService::Stub::PrepareAsyncListRaw(::grpc::ClientContext* context, const ::containers::ListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::ListResponse, ::containers::ListRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_List_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::ListResponse>* ContainerService::Stub::AsyncListRaw(::grpc::ClientContext* context, const ::containers::ListRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ContainerService::Stub::Stats(::grpc::ClientContext* context, const ::containers::StatsRequest& request, ::containers::StatsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::StatsRequest, ::containers::StatsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Stats_, context, request, response);
}

void ContainerService::Stub::async::Stats(::grpc::ClientContext* context, const ::containers::StatsRequest* request, ::containers::StatsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::StatsRequest, ::containers::StatsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Stats_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::Stats(::grpc::ClientContext* context, const ::containers::StatsRequest* request, ::containers::StatsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Stats_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::StatsResponse>* ContainerService::Stub::PrepareAsyncStatsRaw(::grpc::ClientContext* context, const ::containers::StatsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::StatsResponse, ::containers::StatsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Stats_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::StatsResponse>* ContainerService::Stub::AsyncStatsRaw(::grpc::ClientContext* context, const ::containers::StatsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStatsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ContainerService::Stub::Wait(::grpc::ClientContext* context, const ::containers::WaitRequest& request, ::containers::WaitResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::WaitRequest, ::containers::WaitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Wait_, context, request, response);
}

void ContainerService::Stub::async::Wait(::grpc::ClientContext* context, const ::containers::WaitRequest* request, ::containers::WaitResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::WaitRequest, ::containers::WaitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Wait_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::Wait(::grpc::ClientContext* context, const ::containers::WaitRequest* request, ::containers::WaitResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Wait_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::WaitResponse>* ContainerService::Stub::PrepareAsyncWaitRaw(::grpc::ClientContext* context, const ::containers::WaitRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::WaitResponse, ::containers::WaitRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Wait_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::WaitResponse>* ContainerService::Stub::AsyncWaitRaw(::grpc::ClientContext* context, const ::containers::WaitRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncWaitRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::containers::Event>* ContainerService::Stub::EventsRaw(::grpc::ClientContext* context, const ::containers::EventsRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::containers::Event>::Create(channel_.get(), rpcmethod_Events_, context, request);
}

void ContainerService::Stub::async::Events(::grpc::ClientContext* context, const ::containers::EventsRequest* request, ::grpc::ClientReadReactor< ::containers::Event>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::containers::Event>::Create(stub_->channel_.get(), stub_->rpcmethod_Events_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::containers::Event>* ContainerService::Stub::AsyncEventsRaw(::grpc::ClientContext* context, const ::containers::EventsRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::containers::Event>::Create(channel_.get(), cq, rpcmethod_Events_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::containers::Event>* ContainerService::Stub::PrepareAsyncEventsRaw(::grpc::ClientContext* context, const ::containers::EventsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::containers::Event>::Create(channel_.get(), cq, rpcmethod_Events_, context, request, false, nullptr);
}

::grpc::Status ContainerService::Stub::Exec(::grpc::ClientContext* context, const ::containers::ExecRequest& request, ::containers::ExecResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::ExecRequest, ::containers::ExecResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Exec_, context, request, response);
}

void ContainerService::Stub::async::Exec(::grpc::ClientContext* context, const ::containers::ExecRequest* request, ::containers::ExecResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::ExecRequest, ::containers::ExecResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Exec_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::Exec(::grpc::ClientContext* context, const ::containers::ExecRequest* request, ::containers::ExecResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Exec_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::ExecResponse>* ContainerService::Stub::PrepareAsyncExecRaw(::grpc::ClientContext* context, const ::containers::ExecRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::ExecResponse, ::containers::ExecRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Exec_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::ExecResponse>* ContainerService::Stub::AsyncExecRaw(::grpc::ClientContext* context, const ::containers::ExecRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExecRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::containers::RemoteExecRequest, ::containers::RemoteExecResponse>* ContainerService::Stub::RemoteExecRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::containers::RemoteExecRequest, ::containers::RemoteExecResponse>::Create(channel_.get(), rpcmethod_RemoteExec_, context);
}

void ContainerService::Stub::async::RemoteExec(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::containers::RemoteExecRequest,::containers::RemoteExecResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::containers::RemoteExecRequest,::containers::RemoteExecResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_RemoteExec_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::containers::RemoteExecRequest, ::containers::RemoteExecResponse>* ContainerService::Stub::AsyncRemoteExecRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::containers::RemoteExecRequest, ::containers::RemoteExecResponse>::Create(channel_.get(), cq, rpcmethod_RemoteExec_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::containers::RemoteExecRequest, ::containers::RemoteExecResponse>* ContainerService::Stub::PrepareAsyncRemoteExecRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::containers::RemoteExecRequest, ::containers::RemoteExecResponse>::Create(channel_.get(), cq, rpcmethod_RemoteExec_, context, false, nullptr);
}

::grpc::Status ContainerService::Stub::Version(::grpc::ClientContext* context, const ::containers::VersionRequest& request, ::containers::VersionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::VersionRequest, ::containers::VersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Version_, context, request, response);
}

void ContainerService::Stub::async::Version(::grpc::ClientContext* context, const ::containers::VersionRequest* request, ::containers::VersionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::VersionRequest, ::containers::VersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Version_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::Version(::grpc::ClientContext* context, const ::containers::VersionRequest* request, ::containers::VersionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Version_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::VersionResponse>* ContainerService::Stub::PrepareAsyncVersionRaw(::grpc::ClientContext* context, const ::containers::VersionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::VersionResponse, ::containers::VersionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Version_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::VersionResponse>* ContainerService::Stub::AsyncVersionRaw(::grpc::ClientContext* context, const ::containers::VersionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncVersionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ContainerService::Stub::Info(::grpc::ClientContext* context, const ::containers::InfoRequest& request, ::containers::InfoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::InfoRequest, ::containers::InfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Info_, context, request, response);
}

void ContainerService::Stub::async::Info(::grpc::ClientContext* context, const ::containers::InfoRequest* request, ::containers::InfoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::InfoRequest, ::containers::InfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Info_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::Info(::grpc::ClientContext* context, const ::containers::InfoRequest* request, ::containers::InfoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Info_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::InfoResponse>* ContainerService::Stub::PrepareAsyncInfoRaw(::grpc::ClientContext* context, const ::containers::InfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::InfoResponse, ::containers::InfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Info_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::InfoResponse>* ContainerService::Stub::AsyncInfoRaw(::grpc::ClientContext* context, const ::containers::InfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ContainerService::Stub::Update(::grpc::ClientContext* context, const ::containers::UpdateRequest& request, ::containers::UpdateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::UpdateRequest, ::containers::UpdateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Update_, context, request, response);
}

void ContainerService::Stub::async::Update(::grpc::ClientContext* context, const ::containers::UpdateRequest* request, ::containers::UpdateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::UpdateRequest, ::containers::UpdateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Update_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::Update(::grpc::ClientContext* context, const ::containers::UpdateRequest* request, ::containers::UpdateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Update_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::UpdateResponse>* ContainerService::Stub::PrepareAsyncUpdateRaw(::grpc::ClientContext* context, const ::containers::UpdateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::UpdateResponse, ::containers::UpdateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Update_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::UpdateResponse>* ContainerService::Stub::AsyncUpdateRaw(::grpc::ClientContext* context, const ::containers::UpdateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::containers::AttachRequest, ::containers::AttachResponse>* ContainerService::Stub::AttachRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::containers::AttachRequest, ::containers::AttachResponse>::Create(channel_.get(), rpcmethod_Attach_, context);
}

void ContainerService::Stub::async::Attach(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::containers::AttachRequest,::containers::AttachResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::containers::AttachRequest,::containers::AttachResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_Attach_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::containers::AttachRequest, ::containers::AttachResponse>* ContainerService::Stub::AsyncAttachRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::containers::AttachRequest, ::containers::AttachResponse>::Create(channel_.get(), cq, rpcmethod_Attach_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::containers::AttachRequest, ::containers::AttachResponse>* ContainerService::Stub::PrepareAsyncAttachRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::containers::AttachRequest, ::containers::AttachResponse>::Create(channel_.get(), cq, rpcmethod_Attach_, context, false, nullptr);
}

::grpc::Status ContainerService::Stub::Restart(::grpc::ClientContext* context, const ::containers::RestartRequest& request, ::containers::RestartResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::RestartRequest, ::containers::RestartResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Restart_, context, request, response);
}

void ContainerService::Stub::async::Restart(::grpc::ClientContext* context, const ::containers::RestartRequest* request, ::containers::RestartResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::RestartRequest, ::containers::RestartResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Restart_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::Restart(::grpc::ClientContext* context, const ::containers::RestartRequest* request, ::containers::RestartResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Restart_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::RestartResponse>* ContainerService::Stub::PrepareAsyncRestartRaw(::grpc::ClientContext* context, const ::containers::RestartRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::RestartResponse, ::containers::RestartRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Restart_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::RestartResponse>* ContainerService::Stub::AsyncRestartRaw(::grpc::ClientContext* context, const ::containers::RestartRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRestartRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ContainerService::Stub::Export(::grpc::ClientContext* context, const ::containers::ExportRequest& request, ::containers::ExportResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::ExportRequest, ::containers::ExportResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Export_, context, request, response);
}

void ContainerService::Stub::async::Export(::grpc::ClientContext* context, const ::containers::ExportRequest* request, ::containers::ExportResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::ExportRequest, ::containers::ExportResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Export_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::Export(::grpc::ClientContext* context, const ::containers::ExportRequest* request, ::containers::ExportResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Export_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::ExportResponse>* ContainerService::Stub::PrepareAsyncExportRaw(::grpc::ClientContext* context, const ::containers::ExportRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::ExportResponse, ::containers::ExportRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Export_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::ExportResponse>* ContainerService::Stub::AsyncExportRaw(::grpc::ClientContext* context, const ::containers::ExportRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExportRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::containers::CopyFromContainerResponse>* ContainerService::Stub::CopyFromContainerRaw(::grpc::ClientContext* context, const ::containers::CopyFromContainerRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::containers::CopyFromContainerResponse>::Create(channel_.get(), rpcmethod_CopyFromContainer_, context, request);
}

void ContainerService::Stub::async::CopyFromContainer(::grpc::ClientContext* context, const ::containers::CopyFromContainerRequest* request, ::grpc::ClientReadReactor< ::containers::CopyFromContainerResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::containers::CopyFromContainerResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_CopyFromContainer_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::containers::CopyFromContainerResponse>* ContainerService::Stub::AsyncCopyFromContainerRaw(::grpc::ClientContext* context, const ::containers::CopyFromContainerRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::containers::CopyFromContainerResponse>::Create(channel_.get(), cq, rpcmethod_CopyFromContainer_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::containers::CopyFromContainerResponse>* ContainerService::Stub::PrepareAsyncCopyFromContainerRaw(::grpc::ClientContext* context, const ::containers::CopyFromContainerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::containers::CopyFromContainerResponse>::Create(channel_.get(), cq, rpcmethod_CopyFromContainer_, context, request, false, nullptr);
}

::grpc::ClientReaderWriter< ::containers::CopyToContainerRequest, ::containers::CopyToContainerResponse>* ContainerService::Stub::CopyToContainerRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::containers::CopyToContainerRequest, ::containers::CopyToContainerResponse>::Create(channel_.get(), rpcmethod_CopyToContainer_, context);
}

void ContainerService::Stub::async::CopyToContainer(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::containers::CopyToContainerRequest,::containers::CopyToContainerResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::containers::CopyToContainerRequest,::containers::CopyToContainerResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_CopyToContainer_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::containers::CopyToContainerRequest, ::containers::CopyToContainerResponse>* ContainerService::Stub::AsyncCopyToContainerRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::containers::CopyToContainerRequest, ::containers::CopyToContainerResponse>::Create(channel_.get(), cq, rpcmethod_CopyToContainer_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::containers::CopyToContainerRequest, ::containers::CopyToContainerResponse>* ContainerService::Stub::PrepareAsyncCopyToContainerRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::containers::CopyToContainerRequest, ::containers::CopyToContainerResponse>::Create(channel_.get(), cq, rpcmethod_CopyToContainer_, context, false, nullptr);
}

::grpc::Status ContainerService::Stub::Rename(::grpc::ClientContext* context, const ::containers::RenameRequest& request, ::containers::RenameResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::RenameRequest, ::containers::RenameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Rename_, context, request, response);
}

void ContainerService::Stub::async::Rename(::grpc::ClientContext* context, const ::containers::RenameRequest* request, ::containers::RenameResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::RenameRequest, ::containers::RenameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Rename_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::Rename(::grpc::ClientContext* context, const ::containers::RenameRequest* request, ::containers::RenameResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Rename_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::RenameResponse>* ContainerService::Stub::PrepareAsyncRenameRaw(::grpc::ClientContext* context, const ::containers::RenameRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::RenameResponse, ::containers::RenameRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Rename_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::RenameResponse>* ContainerService::Stub::AsyncRenameRaw(::grpc::ClientContext* context, const ::containers::RenameRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRenameRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::containers::LogsResponse>* ContainerService::Stub::LogsRaw(::grpc::ClientContext* context, const ::containers::LogsRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::containers::LogsResponse>::Create(channel_.get(), rpcmethod_Logs_, context, request);
}

void ContainerService::Stub::async::Logs(::grpc::ClientContext* context, const ::containers::LogsRequest* request, ::grpc::ClientReadReactor< ::containers::LogsResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::containers::LogsResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_Logs_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::containers::LogsResponse>* ContainerService::Stub::AsyncLogsRaw(::grpc::ClientContext* context, const ::containers::LogsRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::containers::LogsResponse>::Create(channel_.get(), cq, rpcmethod_Logs_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::containers::LogsResponse>* ContainerService::Stub::PrepareAsyncLogsRaw(::grpc::ClientContext* context, const ::containers::LogsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::containers::LogsResponse>::Create(channel_.get(), cq, rpcmethod_Logs_, context, request, false, nullptr);
}

::grpc::Status ContainerService::Stub::Resize(::grpc::ClientContext* context, const ::containers::ResizeRequest& request, ::containers::ResizeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::containers::ResizeRequest, ::containers::ResizeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Resize_, context, request, response);
}

void ContainerService::Stub::async::Resize(::grpc::ClientContext* context, const ::containers::ResizeRequest* request, ::containers::ResizeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::containers::ResizeRequest, ::containers::ResizeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Resize_, context, request, response, std::move(f));
}

void ContainerService::Stub::async::Resize(::grpc::ClientContext* context, const ::containers::ResizeRequest* request, ::containers::ResizeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Resize_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::containers::ResizeResponse>* ContainerService::Stub::PrepareAsyncResizeRaw(::grpc::ClientContext* context, const ::containers::ResizeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::containers::ResizeResponse, ::containers::ResizeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Resize_, context, request);
}

::grpc::ClientAsyncResponseReader< ::containers::ResizeResponse>* ContainerService::Stub::AsyncResizeRaw(::grpc::ClientContext* context, const ::containers::ResizeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncResizeRaw(context, request, cq);
  result->StartCall();
  return result;
}

ContainerService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::CreateRequest, ::containers::CreateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::CreateRequest* req,
             ::containers::CreateResponse* resp) {
               return service->Create(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::StartRequest, ::containers::StartResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::StartRequest* req,
             ::containers::StartResponse* resp) {
               return service->Start(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[2],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< ContainerService::Service, ::containers::RemoteStartRequest, ::containers::RemoteStartResponse>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::containers::RemoteStartResponse,
             ::containers::RemoteStartRequest>* stream) {
               return service->RemoteStart(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::TopRequest, ::containers::TopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::TopRequest* req,
             ::containers::TopResponse* resp) {
               return service->Top(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::StopRequest, ::containers::StopResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::StopRequest* req,
             ::containers::StopResponse* resp) {
               return service->Stop(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::KillRequest, ::containers::KillResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::KillRequest* req,
             ::containers::KillResponse* resp) {
               return service->Kill(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::DeleteRequest, ::containers::DeleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::DeleteRequest* req,
             ::containers::DeleteResponse* resp) {
               return service->Delete(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::PauseRequest, ::containers::PauseResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::PauseRequest* req,
             ::containers::PauseResponse* resp) {
               return service->Pause(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::ResumeRequest, ::containers::ResumeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::ResumeRequest* req,
             ::containers::ResumeResponse* resp) {
               return service->Resume(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::InspectContainerRequest, ::containers::InspectContainerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::InspectContainerRequest* req,
             ::containers::InspectContainerResponse* resp) {
               return service->Inspect(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::ListRequest, ::containers::ListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::ListRequest* req,
             ::containers::ListResponse* resp) {
               return service->List(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::StatsRequest, ::containers::StatsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::StatsRequest* req,
             ::containers::StatsResponse* resp) {
               return service->Stats(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::WaitRequest, ::containers::WaitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::WaitRequest* req,
             ::containers::WaitResponse* resp) {
               return service->Wait(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[13],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ContainerService::Service, ::containers::EventsRequest, ::containers::Event>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::EventsRequest* req,
             ::grpc::ServerWriter<::containers::Event>* writer) {
               return service->Events(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::ExecRequest, ::containers::ExecResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::ExecRequest* req,
             ::containers::ExecResponse* resp) {
               return service->Exec(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[15],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< ContainerService::Service, ::containers::RemoteExecRequest, ::containers::RemoteExecResponse>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::containers::RemoteExecResponse,
             ::containers::RemoteExecRequest>* stream) {
               return service->RemoteExec(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::VersionRequest, ::containers::VersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::VersionRequest* req,
             ::containers::VersionResponse* resp) {
               return service->Version(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::InfoRequest, ::containers::InfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::InfoRequest* req,
             ::containers::InfoResponse* resp) {
               return service->Info(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[18],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::UpdateRequest, ::containers::UpdateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::UpdateRequest* req,
             ::containers::UpdateResponse* resp) {
               return service->Update(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[19],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< ContainerService::Service, ::containers::AttachRequest, ::containers::AttachResponse>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::containers::AttachResponse,
             ::containers::AttachRequest>* stream) {
               return service->Attach(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[20],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::RestartRequest, ::containers::RestartResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::RestartRequest* req,
             ::containers::RestartResponse* resp) {
               return service->Restart(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[21],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::ExportRequest, ::containers::ExportResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::ExportRequest* req,
             ::containers::ExportResponse* resp) {
               return service->Export(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[22],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ContainerService::Service, ::containers::CopyFromContainerRequest, ::containers::CopyFromContainerResponse>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::CopyFromContainerRequest* req,
             ::grpc::ServerWriter<::containers::CopyFromContainerResponse>* writer) {
               return service->CopyFromContainer(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[23],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< ContainerService::Service, ::containers::CopyToContainerRequest, ::containers::CopyToContainerResponse>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::containers::CopyToContainerResponse,
             ::containers::CopyToContainerRequest>* stream) {
               return service->CopyToContainer(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[24],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::RenameRequest, ::containers::RenameResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::RenameRequest* req,
             ::containers::RenameResponse* resp) {
               return service->Rename(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[25],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ContainerService::Service, ::containers::LogsRequest, ::containers::LogsResponse>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::LogsRequest* req,
             ::grpc::ServerWriter<::containers::LogsResponse>* writer) {
               return service->Logs(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ContainerService_method_names[26],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ContainerService::Service, ::containers::ResizeRequest, ::containers::ResizeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ContainerService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::containers::ResizeRequest* req,
             ::containers::ResizeResponse* resp) {
               return service->Resize(ctx, req, resp);
             }, this)));
}

ContainerService::Service::~Service() {
}

::grpc::Status ContainerService::Service::Create(::grpc::ServerContext* context, const ::containers::CreateRequest* request, ::containers::CreateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Start(::grpc::ServerContext* context, const ::containers::StartRequest* request, ::containers::StartResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::RemoteStart(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::containers::RemoteStartResponse, ::containers::RemoteStartRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Top(::grpc::ServerContext* context, const ::containers::TopRequest* request, ::containers::TopResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Stop(::grpc::ServerContext* context, const ::containers::StopRequest* request, ::containers::StopResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Kill(::grpc::ServerContext* context, const ::containers::KillRequest* request, ::containers::KillResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Delete(::grpc::ServerContext* context, const ::containers::DeleteRequest* request, ::containers::DeleteResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Pause(::grpc::ServerContext* context, const ::containers::PauseRequest* request, ::containers::PauseResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Resume(::grpc::ServerContext* context, const ::containers::ResumeRequest* request, ::containers::ResumeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Inspect(::grpc::ServerContext* context, const ::containers::InspectContainerRequest* request, ::containers::InspectContainerResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::List(::grpc::ServerContext* context, const ::containers::ListRequest* request, ::containers::ListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Stats(::grpc::ServerContext* context, const ::containers::StatsRequest* request, ::containers::StatsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Wait(::grpc::ServerContext* context, const ::containers::WaitRequest* request, ::containers::WaitResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Events(::grpc::ServerContext* context, const ::containers::EventsRequest* request, ::grpc::ServerWriter< ::containers::Event>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Exec(::grpc::ServerContext* context, const ::containers::ExecRequest* request, ::containers::ExecResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::RemoteExec(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::containers::RemoteExecResponse, ::containers::RemoteExecRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Version(::grpc::ServerContext* context, const ::containers::VersionRequest* request, ::containers::VersionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Info(::grpc::ServerContext* context, const ::containers::InfoRequest* request, ::containers::InfoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Update(::grpc::ServerContext* context, const ::containers::UpdateRequest* request, ::containers::UpdateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Attach(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::containers::AttachResponse, ::containers::AttachRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Restart(::grpc::ServerContext* context, const ::containers::RestartRequest* request, ::containers::RestartResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Export(::grpc::ServerContext* context, const ::containers::ExportRequest* request, ::containers::ExportResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::CopyFromContainer(::grpc::ServerContext* context, const ::containers::CopyFromContainerRequest* request, ::grpc::ServerWriter< ::containers::CopyFromContainerResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::CopyToContainer(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::containers::CopyToContainerResponse, ::containers::CopyToContainerRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Rename(::grpc::ServerContext* context, const ::containers::RenameRequest* request, ::containers::RenameResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Logs(::grpc::ServerContext* context, const ::containers::LogsRequest* request, ::grpc::ServerWriter< ::containers::LogsResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ContainerService::Service::Resize(::grpc::ServerContext* context, const ::containers::ResizeRequest* request, ::containers::ResizeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace containers

